// <auto-generated />
using System;
using LogisticDashboard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticDashboard.API.Migrations
{
    [DbContext(typeof(LogisticDashboardAPIContext))]
    [Migration("20251002073902_AddVesselMapRouteVesselName")]
    partial class AddVesselMapRouteVesselName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticDashboard.Core.AirFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATA_Port_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AWB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Del")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ETA_BIPH_Manual_Computation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Earliest_Shortage_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flight_Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flight_Status_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Forwarder_Courier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Freight_Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Have_Arrangement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Import_Permit_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Import_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Invoice_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latest_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Pkgs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Ship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("System_Update")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("With_Special_Permit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AirFreightScheduleMonitoring");
                });

            modelBuilder.Entity("LogisticDashboard.Core.BerthingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Normal_Range_VesselsAtAnchorage")
                        .HasColumnType("text");

                    b.Property<string>("Normal_Range_VesselsAtBerth")
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselsAtAnchorage")
                        .HasColumnType("text");

                    b.Property<string>("VesselsAtBerth")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BerthingStatus");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Incoterms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationCustoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationTerminalCharges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationTrucking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OceanFreightAirFreight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginCustoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginTerminalCharges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginTruckings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Incoterms");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PortUtilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Overall_Yard_Utilization")
                        .HasColumnType("integer");

                    b.Property<int>("PortId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vessels_At_Anchorage_Waiting")
                        .HasColumnType("integer");

                    b.Property<int>("Vessels_At_Berth")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("PortUtilization");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Ports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Normal_Range_Overall_Yard_Utilization")
                        .HasColumnType("integer");

                    b.Property<int>("Normal_Range_Vessels_At_Anchorage")
                        .HasColumnType("integer");

                    b.Property<int>("Normal_Range_Vessels_At_Berth")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Routes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteName")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SailingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DelayArrival")
                        .HasColumnType("integer");

                    b.Property<int?>("DelayDeparture")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestETAMNL")
                        .HasColumnType("text");

                    b.Property<string>("LatestETD")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<string>("OriginalETAMNL")
                        .HasColumnType("text");

                    b.Property<string>("OriginalETD")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransitDays")
                        .HasColumnType("text");

                    b.Property<string>("VesselName")
                        .HasColumnType("text");

                    b.Property<string>("VoyNo")
                        .HasColumnType("text");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("SailingSchedule");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SeaFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Delivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Leadtime_ATA_Port_ATA_BIPH_exclude_weekend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BERTH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Based_On_BERTH_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bobtail_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrier_Forwarded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_Size_No_Of_PKGS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date_Return_of_Empty_Cntr")
                        .HasColumnType("text");

                    b.Property<string>("ETA_BIPH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Earliest_Shortage_Date")
                        .HasColumnType("text");

                    b.Property<string>("Final_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeTime_Valid_Until")
                        .HasColumnType("text");

                    b.Property<string>("Have_Job_Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latest_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode_Of_Shipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETD_ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_of_Free_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_with_Detention_Estimate_Only")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orig_RDD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port_Of_Discharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority_Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Random_Boolean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Request_to_Unload_AM_or_PM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Ship")
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Pick_Up_Date")
                        .HasColumnType("text");

                    b.Property<string>("Shipment_Processing_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transit_Days_ATD_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("With_Special_Permit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SeaFreightScheduleMonitoring");
                });

            modelBuilder.Entity("LogisticDashboard.Core.VesselRouteMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VesselRouteMap");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PortUtilization", b =>
                {
                    b.HasOne("LogisticDashboard.Core.Ports", "Port")
                        .WithMany("PortUtilizations")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SailingSchedule", b =>
                {
                    b.HasOne("LogisticDashboard.Core.Routes", "Route")
                        .WithMany("SailingSchedule")
                        .HasForeignKey("RouteId");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Ports", b =>
                {
                    b.Navigation("PortUtilizations");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Routes", b =>
                {
                    b.Navigation("SailingSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
