// <auto-generated />
using System;
using LogisticDashboard.API.Data;
using LogisticDashboard.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticDashboard.API.Migrations
{
    [DbContext(typeof(LogisticDashboardAPIContext))]
    [Migration("20260114090755_ImportReviseDB")]
    partial class ImportReviseDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticDashboard.Core.AirFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATA_Port_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AWB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Del")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ETA_BIPH_Manual_Computation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Earliest_Shortage_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flight_Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flight_Status_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Forwarder_Courier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Freight_Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Have_Arrangement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Import_Permit_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Import_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Invoice_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latest_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Pkgs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Ship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("System_Update")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("With_Special_Permit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AirFreightScheduleMonitoring");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Announcements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("LogisticDashboard.Core.BerthingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Normal_Range_VesselsAtAnchorage")
                        .HasColumnType("text");

                    b.Property<string>("Normal_Range_VesselsAtBerth")
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselsAtAnchorage")
                        .HasColumnType("text");

                    b.Property<string>("VesselsAtBerth")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BerthingStatus");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ContainerVisualization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Container_Image_Link")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContainerVisualization");
                });

            modelBuilder.Entity("LogisticDashboard.Core.CourierInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BIPH_Account_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourierImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CourierInformation");
                });

            modelBuilder.Entity("LogisticDashboard.Core.DHL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DHL");
                });

            modelBuilder.Entity("LogisticDashboard.Core.DeliveryLeadtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomsClearanceLeadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalLeadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselTransitLeadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DeliveryLeadtime");
                });

            modelBuilder.Entity("LogisticDashboard.Core.DeliveryLeadtimeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualFYAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Actual_Ave")
                        .HasColumnType("numeric");

                    b.Property<int?>("FY")
                        .HasColumnType("integer");

                    b.Property<string>("LeadtimeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("NoOfBLFY")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("No_Of_BL")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetFYMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetFYMin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Target_Max")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Target_Min")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DeliveryLeadtimeData");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Flowchart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrawflowData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Flowchart");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportBerthingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("BIPH_Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Original_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PortId")
                        .HasColumnType("integer");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Revised_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("ImportBerthingStatus");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportDashboards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("BIPH_Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Original_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Revised_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportDashboards");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BIL_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BIPH_Action")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Original_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasons")
                        .HasColumnType("text");

                    b.Property<DateTime>("Revised_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportDelivery");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportDeliveryDashboards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("BIPH_Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Original_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Revised_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportDeliveryDashboards");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportPICInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeOfShipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingMainPICStaff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingSubPICStaff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportPICInformation");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportPortUtilizationManila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("BIPH_Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Original_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Revised_ETA_Port")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportPortUtilizationManila");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Incoterms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationCustoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationTerminalCharges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationTrucking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OceanFreightAirFreight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginCustoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginTerminalCharges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginTruckings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Incoterms");
                });

            modelBuilder.Entity("LogisticDashboard.Core.LogisticCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KGS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalUSD")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LogisticCost");
                });

            modelBuilder.Entity("LogisticDashboard.Core.LogisticCostCourierAF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogisticCostCourierAF");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ModeOfShipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FCLProcessFlow_Image_Link")
                        .HasColumnType("text");

                    b.Property<string>("LCLProcessFlow_Image_Link")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModeOfShipment");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PHPortMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationPort")
                        .HasColumnType("text");

                    b.Property<Coordinates>("DestinationPortCoordinates")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Coordinates>("OriginPortCoordinates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PictureLocation")
                        .HasColumnType("text");

                    b.Property<string>("SailingLeadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PHPortMap");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PhilippineHolidays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency_Office")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Holiday")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhilippineHolidays");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PortUtilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Overall_Yard_Utilization")
                        .HasColumnType("integer");

                    b.Property<int>("PortId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vessels_At_Anchorage_Waiting")
                        .HasColumnType("integer");

                    b.Property<int>("Vessels_At_Berth")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("PortUtilization");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Ports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Normal_Range_Overall_Yard_Utilization")
                        .HasColumnType("integer");

                    b.Property<int>("Normal_Range_Vessels_At_Anchorage")
                        .HasColumnType("integer");

                    b.Property<int>("Normal_Range_Vessels_At_Berth")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Routes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteName")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SailingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DelayArrival")
                        .HasColumnType("integer");

                    b.Property<int?>("DelayDeparture")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestETAMNL")
                        .HasColumnType("text");

                    b.Property<string>("LatestETD")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<string>("OriginalETAMNL")
                        .HasColumnType("text");

                    b.Property<string>("OriginalETD")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransitDays")
                        .HasColumnType("text");

                    b.Property<string>("VesselName")
                        .HasColumnType("text");

                    b.Property<string>("VoyNo")
                        .HasColumnType("text");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("SailingSchedule");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SeaFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Delivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Leadtime_ATA_Port_ATA_BIPH_exclude_weekend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BERTH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Based_On_BERTH_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bobtail_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrier_Forwarded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_Size_No_Of_PKGS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date_Return_of_Empty_Cntr")
                        .HasColumnType("text");

                    b.Property<string>("ETA_BIPH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Earliest_Shortage_Date")
                        .HasColumnType("text");

                    b.Property<string>("Final_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeTime_Valid_Until")
                        .HasColumnType("text");

                    b.Property<string>("Have_Job_Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latest_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode_Of_Shipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETD_ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_of_Free_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_with_Detention_Estimate_Only")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orig_RDD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port_Of_Discharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority_Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Random_Boolean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Request_to_Unload_AM_or_PM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Ship")
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Pick_Up_Date")
                        .HasColumnType("text");

                    b.Property<string>("Shipment_Processing_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transit_Days_ATD_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vessel_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Status_BIPH_Action")
                        .HasColumnType("text");

                    b.Property<string>("With_Special_Permit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SeaFreightScheduleMonitoring");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ShippingInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileLinkEnglish")
                        .HasColumnType("text");

                    b.Property<string>("FileLinkJapanese")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingInstructionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShippingInstruction");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("PortalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogisticDashboard.Core.VesselRouteMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Coordinates>("DestinationPortCoordinates")
                        .HasColumnType("jsonb");

                    b.Property<string>("DestinationPortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Import_Processing_Leadtime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Coordinates>("OriginPortCoordinates")
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginPortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Origin_To_Destination_Port")
                        .HasColumnType("integer");

                    b.Property<string>("PictureLocation")
                        .HasColumnType("text");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<int?>("Total_Leadtime")
                        .HasColumnType("integer");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VesselRouteMap");
                });

            modelBuilder.Entity("LogisticDashboard.Core.ImportBerthingStatus", b =>
                {
                    b.HasOne("LogisticDashboard.Core.Ports", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("LogisticDashboard.Core.PortUtilization", b =>
                {
                    b.HasOne("LogisticDashboard.Core.Ports", "Port")
                        .WithMany("PortUtilizations")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SailingSchedule", b =>
                {
                    b.HasOne("LogisticDashboard.Core.Routes", "Route")
                        .WithMany("SailingSchedule")
                        .HasForeignKey("RouteId");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Ports", b =>
                {
                    b.Navigation("PortUtilizations");
                });

            modelBuilder.Entity("LogisticDashboard.Core.Routes", b =>
                {
                    b.Navigation("SailingSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
