// <auto-generated />
using LogisticDashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticDashboard.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807231706_AllStrings")]
    partial class AllStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticDashboard.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SeaFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATB_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Delivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Leadtime_ATA_Port_ATA_BIPH_exclude_weekend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actual_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BERTH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Based_On_BERTH_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bobtail_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrier_Forwarded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_Size_No_Of_PKGS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date_Return_of_Empty_Cntr")
                        .HasColumnType("text");

                    b.Property<string>("ETA_BIPH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Earliest_Shortage_Date")
                        .HasColumnType("text");

                    b.Property<string>("Final_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeTime_Valid_Until")
                        .HasColumnType("text");

                    b.Property<string>("Have_Job_Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latest_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode_Of_Shipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETA_ATB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_Of_Days_Delayed_ETD_ATD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_of_Free_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("No_of_Days_with_Detention_Estimate_Only")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orig_RDD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Original_ETD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port_Of_Discharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority_Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Random_Boolean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Request_to_Unload_AM_or_PM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Ship")
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Date_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Del_Time_To_Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requested_Pick_Up_Date")
                        .HasColumnType("text");

                    b.Property<string>("Shipment_Processing_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step_6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transit_Days_ATD_ATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("With_Special_Permit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SeaFreightScheduleMonitoring");
                });
#pragma warning restore 612, 618
        }
    }
}
