// <auto-generated />
using System;
using LogisticDashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticDashboard.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticDashboard.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LogisticDashboard.Core.SeaFreightScheduleMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ATA")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ATB_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ATB_Time")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("ATD")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Actual_Del_Time_To_Trucker")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Actual_Delivery")
                        .HasColumnType("date");

                    b.Property<decimal>("Actual_Leadtime_ATA_Port_ATA_BIPH_exclude_weekend")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Actual_Status")
                        .HasColumnType("date");

                    b.Property<string>("BERTH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Based_On_BERTH_BIPH_Leadtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bobtail_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrier_Forwarded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Container_Size_No_Of_PKGS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Date_Return_of_Empty_Cntr")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ETA_BIPH")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Earliest_Shortage_Date")
                        .HasColumnType("date");

                    b.Property<string>("Final_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FreeTime_Valid_Until")
                        .HasColumnType("date");

                    b.Property<bool>("Have_Job_Operation")
                        .HasColumnType("boolean");

                    b.Property<string>("INV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Latest_ETA")
                        .HasColumnType("date");

                    b.Property<string>("Mode_Of_Shipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("No_of_Days_of_Free_Time")
                        .HasColumnType("numeric");

                    b.Property<decimal>("No_of_Days_with_Detention_Estimate_Only")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Orig_RDD")
                        .HasColumnType("date");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Original_ETA")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Original_ETD")
                        .HasColumnType("date");

                    b.Property<string>("Port_Of_Discharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority_Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Random_Boolean")
                        .HasColumnType("boolean");

                    b.Property<string>("Request_to_Unload_AM_or_PM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Requested_Del_Date_To_Ship")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Requested_Del_Date_To_Trucker")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Requested_Del_Time_To_Trucker")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly?>("Requested_Pick_Up_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Shipment_Processing_Remarks")
                        .HasColumnType("date");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Step_1")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Step_2")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Step_3")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Step_4")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Step_5")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Step_6")
                        .HasColumnType("date");

                    b.Property<string>("Trucker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vessel_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("With_Special_Permit")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SeaFreightScheduleMonitoring");
                });
#pragma warning restore 612, 618
        }
    }
}
